name: Publish to WordPress

on:
  push:
    branches:
      - main
    paths:
      - 'blog/**.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: WordPress Posts Sync
        uses: devcro/wordpress-posts-sync@v1
        with:
          wp_url: ${{ secrets.WP_URL }}
          wp_username: ${{ secrets.WP_USER }}
          wp_password: ${{ secrets.WP_PASSWORD }}
          post_status: 'publish' # or 'draft' if you want to review first
          folder: 'blog'
